project_id = "zoominfo-project"
region     = "us-central1"
zone       = "us-central1-a"
bucket_name = "zinfo-gcs-bucket"
service_account_key = "/home/jdeesh735/sa_tf/zoominfo/zinfo-sa_zoominfo-project.json"
